//////////////////////////////////////////////////////////////////////////////
// We are creating a driver class for driving the inputs here by using mailbox 
// we will get the randomized inputs from generator  are generated by mailbox 
// by put method and by using transaction class we are getting by get method
// in driver class.
//
/////////////////////////////////////////////////////////////////////////////

class driver;
  // Mailbox from generator to driver
  mailbox #(transaction) gen2drv;
  virtual dual_port #(12, 10) dp;

  // Constructor: keep parameter order consistent with the member above.
  function new(mailbox #(transaction) gen2drv, virtual dual_port #(12, 10) dp);
    this.gen2drv = gen2drv;
    this.dp      = dp;
  endfunction

  // Optional: initial defaults (can be moved to run())
  task init_defaults();
    // Drive safe defaults before starting
    dp.i_en_a   <= 1'b0;
    dp.i_we_a   <= 1'b0;
    dp.i_addr_a <= '0;
    dp.i_din_a  <= '0;

    dp.i_en_b   <= 1'b0;
    dp.i_we_b   <= 1'b0;
    dp.i_addr_b <= '0;
    dp.i_din_b  <= '0;
  endtask

  task run();
    transaction t;

    // Initialize outputs once
    init_defaults();

    forever begin
      // Block until we receive the next item
      gen2drv.get(t);
      @(negedge dp.i_clk_a);
      dp.i_en_a   <= t.i_en_a;
      dp.i_we_a   <= t.i_we_a;
      dp.i_din_a  <= t.i_din_a;
      dp.i_addr_a <= t.i_addr_a;

      @(negedge dp.i_clk_b);
      dp.i_en_b   <= t.i_en_b;
      dp.i_we_b   <= t.i_we_b;
      dp.i_din_b  <= t.i_din_b;
      dp.i_addr_b <= t.i_addr_b;

          end
  endtask
endclass

